# Generated by Django 5.1.4 on 2025-01-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="cv_file",
            field=models.FileField(blank=True, upload_to="index/pdf"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="foto_perfil",
            field=models.ImageField(upload_to="index/images"),
        ),
    ]
